# Generated by Django 3.2 on 2021-05-02 05:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import salesrep.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('Television', 'Television'), ('Refrigerator', 'Refrigerator')], max_length=60)),
                ('model_num', models.CharField(default='', max_length=60)),
                ('avail', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='OrderIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.CharField(default='OrderNumber', editable=False, max_length=100)),
                ('order_id', models.IntegerField(default=0, null=True)),
                ('cust_name', models.CharField(default='', max_length=60)),
                ('cust_add', models.CharField(default='', max_length=60)),
                ('distance', salesrep.models.RangeField(default=0.1, max_val=10.1, min_val=0.1)),
                ('order_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('estimated_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('team', models.CharField(choices=[('A', 'Team A'), ('B', 'Team B')], default='get_team', max_length=60)),
                ('status', models.CharField(choices=[('Pending', 'Delivery Pending'), ('WithDrawm', 'Rejected by Company'), ('Rejected', 'Rejected by customer'), ('Delivered', 'Delivery completed')], default='Pending', max_length=60)),
                ('total_price', models.FloatField(default=0.0)),
            ],
            options={
                'get_latest_by': 'order_time',
            },
        ),
        migrations.CreateModel(
            name='ItemsIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(default='', max_length=60)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.FloatField(default=0.0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='salesrep.orderintake')),
            ],
        ),
    ]
